<html>
  <head>
    <link type="text/css" rel="stylesheet" href="/stylesheets/main.css" />
  </head>
  <body>
  	{{ page_header }}
    <h3>
      Bonjour{% if user %}, {{ user }}{% endif %}!
    </h3>
    <h4>
      Utilisation
    </h4>
    Cliquez sur <a href="/recherche">Recherche</a> pour obtenir la liste de tous les livres d'occasion offerts sur le site.
    <p>
    Cliquez sur <a href="/vendre">Mes Livres</a> pour g&eacute;rer la liste de vos livres &agrave; vendre.

		{{ page_footer }}
  </body>
</html>
