<html>
  <head>
    <link type="text/css" rel="stylesheet" href="/stylesheets/main.css" />
    <title>
      Listes Officielles | Livres St-Joseph
    </title>
  </head>
  <body>
    {{ page_header }}
    <h3>
        <a href="http://www.collegestjoseph.ca/fr/materiels.php">Page Officielle</a>
    </h3>
    <h3>
      Listes Officielles (acc&egrave;s rapide)
    </h3>
    <h5>
      <a href="http://www.collegestjoseph.ca/upfiles/manuels2013-2014-sec1.pdf">Secondaire I</a>
    </h5>
    <h5>
      <a href="http://www.collegestjoseph.ca/upfiles/manuels2013-2014-sec2.pdf">Secondaire II</a>
    </h5>
    <h5>
      <a href="http://www.collegestjoseph.ca/upfiles/manuels2013-2014-sec3.pdf">Secondaire III</a>
    </h5>
    <h5>
      <a href="http://www.collegestjoseph.ca/upfiles/manuels2013-2014-sec4.pdf">Secondaire IV</a>
    </h5>
    <h5>
      <a href="http://www.collegestjoseph.ca/upfiles/manuels2013-2014-sec5-2.pdf">Secondaire V</a>
    </h5>
    <h4>
      Utilisation
    </h4>
    Cliquez sur <a href="/recherche?sec=1">Recherche</a> pour obtenir la liste de tous les livres d'occasion offerts sur le site.
    <p>
    Cliquez sur <a href="/vendre">Mes Livres</a> pour g&eacute;rer la liste de vos livres &agrave; vendre.

    {{ page_footer }}
  </body>
</html>
