<html>
  <head>
    <link type="text/css" rel="stylesheet" href="/stylesheets/main.css" />
  </head>
  <body>
  	{{ page_header }}
    <h3>
      Vous devez vous  <a href="{{ url }}">identifier avec un compte Google</a> avant de continuer.
    </h3>
    Si vous n'avez pas de compte Google, <a href="https://www.google.com/accounts"> cr&eacute;&eacute;z-en un ici</a>. C'est gratuit.
    <p>

		{{ page_footer }}
  </body>
</html>
