<html>
  <head>
    <link type="text/css" rel="stylesheet" href="/stylesheets/main.css" />
    <title>
      Connexion | Livres St-Joseph
    </title>
  </head>
  <body>
    {{ page_header }}
    <h3>
      Vous devez vous  <a href="{{ url }}">identifier avec un compte Google</a> avant de continuer.
    </h3>
    Ce site web permet aux parents et &eacute;l&egrave;ves du Coll&egrave;ge Saint-Joseph de Hull d'entrer en contact pour vendre, acheter ou &eacute;changer les livres usag&eacute;s pour le Secondaire I &agrave; V.
    <p>
    Si vous n'avez pas de compte Google, <a href="https://www.google.com/accounts"> cr&eacute;ez-en un ici</a>. C'est gratuit.
    <p>

    {{ page_footer }}
  </body>
</html>
