<html>
  <head>
    <link type="text/css" rel="stylesheet" href="/stylesheets/main.css" />
    <title>
      Recherche | Livres St-Joseph
    </title>
  </head>
  <body>
    {{ page_header }}
    <h3>
      Liste des livres offerts
    </h3>
    Cliquez sur "Contacter le vendeur" si vous d&eacute;sirez entrer en contact avec le propri&eacute;taire des livres. <br>
    Un courriel sera envoy&eacute; aux deux personnes, et les livres seront temporairement retir&eacute;s de la page des recherches.
    <p>
    <em>Note</em>: le Coll&egrave;ge recommande une remise de 20% par ann&eacute;e d'utilisation du livre, si ce dernier est encore en bon &eacute;tat.
    <p>
    <ul id="tabmenu">
      <li>
        {% ifequal sec '1' %}
          <a class="active" href="recherche?sec=1">Secondaire I</a>
        {% else %}
          <a href="recherche?sec=1">Secondaire I</a>
        {% endifequal %}
      </li>
      <li>
        {% ifequal sec '2' %}
          <a class="active" href="recherche?sec=2">Secondaire II</a>
        {% else %}
          <a href="recherche?sec=2">Secondaire II</a>
        {% endifequal %}
      </li>
      <li>
        {% ifequal sec '3' %}
          <a class="active" href="recherche?sec=3">Secondaire III</a>
        {% else %}
          <a href="recherche?sec=3">Secondaire III</a>
        {% endifequal %}
      </li>
      <li>
        {% ifequal sec '4' %}
          <a class="active" href="recherche?sec=4">Secondaire IV</a>
        {% else %}
          <a href="recherche?sec=4">Secondaire IV</a>
        {% endifequal %}
      </li>
      <li>
        {% ifequal sec '5' %}
          <a class="active" href="recherche?sec=5">Secondaire V</a>
        {% else %}
          <a href="recherche?sec=5">Secondaire V</a>
        {% endifequal %}
      </li>
      {% if admin %}
      <li>
        {% ifequal sec '0' %}
          <a class="active" href="recherche?">Tous</a>
        {% else %}
          <a href="recherche?">Tous</a>
        {% endifequal %}
      </li>
      {% endif %}
    </ul>
    <div id="content">
    {% if books %}
      <h4>Ensembles de livres offerts</h4>
      <ol>
      {% for book in books %}
        <li>
            Date: {{ book.date|date:"Y-m-d H:i" }} <br>
            Secondaire: {{ book.grade|escape }} <br>
            Prix: {{ book.price|escape }} $<br>
            {% if book.can_separate %}
              (Peuvent &ecirc;tre vendus &agrave; l'unit&eacute;)
            {% else %}
              (Vendus comme un <b>tout</b>)
            {% endif %}
            <blockquote><pre>{{ book.description|escape }}</pre></blockquote>
            {% ifequal book.owner user %}
              <i>Vous &ecirc;tes le propri&eacute;taire de ces livres.</i><p>
            {% else %}
              <form action="/contactowner" method="post">
                <div>
                  <input type="hidden" name="uuid" value="{{ book.uuid }}" />
                </div>
                <div><input type="submit" value="Contacter le vendeur"></div>
              </form>
              {% if debug %}
              <i>debug</i> vendus par: {{ book.owner }}<p>
              {% endif %}
            {% endifequal %}
            {% if admin %}
              <form action="/deletebooks" method="post">
                <div>
                  <input type="hidden" name="uuid" value="{{ book.uuid }}" />
                </div>
                <div><input type="submit" value="Effacer ces livres"></div>
              </form>
            {% endif %}
        </li>
        <hr>
      {% endfor %}
      </ol>
    {% else %}
      <h4>Aucun ensemble de livres n'est pr&eacute;sentement disponible</h4>
    {% endif %}
    </div>

    {{ page_footer }}
  </body>
</html>
