<html>
  <head>
    <link type="text/css" rel="stylesheet" href="/stylesheets/main.css" />
    <title>
      Mes Livres | Livres St-Joseph
    </title>
  </head>
  <body>
    {{ page_header }}
    <h2>
      Bonjour, {{ user }}.
    </h2>
    Ceci est votre page personnelle. Seul vous y avez acc&egrave;s.
    <p>
    Vous pouvez ajouter des ensembles de livres, les effacer ou les remettre en vente si votre acheteur se d&eacute;siste.

    <h3>
        Mes livres en vente:
    </h3>
    {% if books %}
      <ol>
      {% for book in books %}
        <li>
          Secondaire: {{ book.grade|escape }} <br>
          Prix: {{ book.price|escape }} $ 
          {% if book.can_separate %}
            (Peuvent &ecirc;tre vendus &agrave; l'unit&eacute;)
          {% else %}
            (Vendus comme un <b>tout</b>)
          {% endif %}
          {% if book.buyer %}
            <br>
            Demand&eacute;s par: {{ book.buyer }}
          {% endif %}
          <br>
          <blockquote><pre>{{ book.description|escape }}</pre></blockquote>
          <br>
          <form action="/erasebook" method="post">
            <div>
              <input type="hidden" name="uuid" value="{{ book.uuid }}" />
            </div>
            <div><input type="submit" value="Effacer ces livres"></div>
          </form>
          {% if book.buyer %}
            <form action="/deletebuyer" method="post">
              <div>
                <input type="hidden" name="uuid" value="{{ book.uuid }}" />
              </div>
              <div><input type="submit" value="Remettre ces livres en vente"></div>
            </form>
          {% endif %}
          <p>
        </li>
        <hr>
      {% endfor %}
      </ol>
    {% else %}
      <ul>
        <li><strong>Vous n'avez pas encore de livres &agrave; vendre.</strong></li>
      </ul>
    {% endif %}

    <div>
      <h3>
      Mettre un ensemble de livres &agrave; vendre
      </h3>
      <blockquote>
        <form action="/newbook" method="post">
          <div>
            Description:<br>
            <textarea name="description" rows="20" cols="80">
D&eacute;crivez vos livres &agrave; vendre ici, ainsi que leur condition et tout 
autre d&eacute;tail pertinent.

Note: le Coll&egrave;ge recommande une remise de 20% par ann&eacute;e d'utilisation du livre,
si ce dernier est encore en bon &eacute;tat.

Exemple:
--------------------------------
Manuels de 3e secondaire 
&Eacute;diteur    Titre                              Pay&eacute; Age  Prix 
ERPI       Express yourself                  51.00  2  30.00 
GrCentrPub A walk to remember                 7.00  2   4.00 
Grand Duc  Le Qu&eacute;bec, une histoire ...vol 1  41.00  3  16.00 
Grand Duc  Le Qu&eacute;bec, une histoire ...vol 2  41.00  1  33.00 
Grand Duc  Point de vue math&eacute;matique, vol 1  53.00  1  42.00 
Grand Duc  Point de vue math&eacute;matique, vol 2  53.00  2  31.00 
Grand Duc  Un regard sur la vie, volume 1    37.00  2  22.00 
Grand Duc  Un regard sur la vie, volume 2    37.00  2  22.00 
Hachette&Eacute;d Bled 5e/4e/3e, cours sup&eacute;rieur    33.00  2  20.00 
Longman    The Pearl                         13.00  2   8.00 
                                  Total:    371.00    233.00
--------------------------------
etc...
            </textarea>
          </div>
          <div>
            Secondaire: 
              <input type="radio" name="grade" value="1" CHECKED /> I &nbsp;
              <input type="radio" name="grade" value="2" /> II &nbsp;
              <input type="radio" name="grade" value="3" /> III &nbsp;
              <input type="radio" name="grade" value="4" /> IV &nbsp;
              <input type="radio" name="grade" value="5" /> V &nbsp;
          </div>
          <div>
            Prix pour l'ensemble: <input name="price" cols="5" style="text-align: right" placeholder="233"></textarea> $
            <br>
            Cochez ici <input type="checkbox" name="can_separate" value="true" /> si ces livres peuvent &ecirc;tre vendus s&eacute;par&eacute;ment<br />
          </div>
          <div>
            <input type="submit" value="Ajouter">
          </div>
        </form>
      </blockquote>
    </div>

    {{ page_footer }}
  </body>
</html>
